# Generated by Django 4.1.2 on 2022-10-24 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='database',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='row',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ('-id',)},
        ),
    ]
