# Generated by Django 4.1.2 on 2022-10-24 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_database_options_alter_manager_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='rows',
        ),
        migrations.AddField(
            model_name='row',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.table'),
            preserve_default=False,
        ),
    ]
