# Generated by Django 4.1.2 on 2022-10-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_column_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='type',
            field=models.IntegerField(choices=[(0, 'int'), (1, 'real'), (2, 'char'), (3, 'str'), (4, 'html'), (5, 'strInvl')]),
        ),
    ]
