# Generated by Django 4.1.2 on 2022-10-24 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_column_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='row',
            name='values',
        ),
        migrations.CreateModel(
            name='RowValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.row')),
            ],
        ),
    ]
