# Generated by Django 4.1.2 on 2022-10-24 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_remove_database_tables_remove_manager_databases_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='columns',
        ),
        migrations.AddField(
            model_name='column',
            name='db',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.table'),
            preserve_default=False,
        ),
    ]
